---
# Collector-specific variables

# ELK Docker Stack Configuration
elk_home: "/opt/elk"
docker_compose_version: "3.8"

# Elasticsearch Configuration
elasticsearch_version: "8.11.0"
elasticsearch_heap_size: "2g"
elasticsearch_http_port: 9200
elasticsearch_transport_port: 9300
elasticsearch_cluster_name: "secure-logging-cluster"
elasticsearch_node_name: "elk-node-1"

# Kibana Configuration
kibana_version: "8.11.0"
kibana_port: 5601

# Logstash Configuration
logstash_version: "8.11.0"
logstash_heap_size: "1g"
logstash_port: 5044

# Network Configuration
elk_network_name: "elk-network"

# Rsyslog Server Configuration
rsyslog_server_port: 6514
rsyslog_remote_log_dir: "/var/log/remote"
rsyslog_tls_cert_dir: "/etc/rsyslog.d/tls"
rsyslog_ca_cert: "{{ rsyslog_tls_cert_dir }}/ca-cert.pem"
rsyslog_server_cert: "{{ rsyslog_tls_cert_dir }}/server-cert.pem"
rsyslog_server_key: "{{ rsyslog_tls_cert_dir }}/server-key.pem"
