---
# ELK Docker Stack Default Variables

# Docker Compose Configuration
elk_home: "/opt/elk"
docker_compose_version: "3.8"

# Elasticsearch Configuration
elasticsearch_version: "8.11.0"
elasticsearch_heap_size: "2g"
elasticsearch_http_port: 9200
elasticsearch_transport_port: 9300
elasticsearch_cluster_name: "secure-logging-cluster"
elasticsearch_node_name: "elk-node-1"

# Kibana Configuration
kibana_version: "8.11.0"
kibana_port: 5601

# Logstash Configuration
logstash_version: "8.11.0"
logstash_heap_size: "1g"
logstash_port: 5044

# Network Configuration
elk_network_name: "elk-network"
